"""Structured logging system with benchmark integration."""

from .benchmark_integration import install_benchmark_logging
from .benchmark_integration import uninstall_benchmark_logging
from .benchmark_tools import export_benchmark_report_json, summarize_benchmarks
from .core import (
    LogLevel,
    LogRecord,
    LogStore,
    StructuredLogger,
    clear,
    current_session_dir,
    export_json,
    get_logger,
    latest_session_dir,
    list_persistence_sessions,
    read_session_log_records,
    list_session_tasks,
    query,
    read_persistence_session,
    read_task_replay_records,
    records,
    records_from,
    replay,
    start_persistence_session,
    stop_persistence_session,
    tail_records,
)

__all__ = [
    "LogLevel",
    "LogRecord",
    "LogStore",
    "StructuredLogger",
    "clear",
    "current_session_dir",
    "export_benchmark_report_json",
    "export_json",
    "get_logger",
    "install_benchmark_logging",
    "latest_session_dir",
    "list_persistence_sessions",
    "read_session_log_records",
    "list_session_tasks",
    "query",
    "read_persistence_session",
    "read_task_replay_records",
    "records",
    "records_from",
    "replay",
    "start_persistence_session",
    "stop_persistence_session",
    "summarize_benchmarks",
    "tail_records",
    "uninstall_benchmark_logging",
]
